commonLabels:
  environment: prd

namespace: mar11-prd

namePrefix: prd-

resources:
- ../../base

patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: app1-deployment
  path: patch.yaml
