apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: app1-rollout
spec:
  replicas: 1
  strategy:
    canary:
      canaryService: "{{ .Values.app1.service_canary }}"
      stableService: "{{ .Values.app1.service_stable }}"
      trafficRouting:
        nginx:
          stableIngress: app-ingress
      steps:
        - setWeight: 50
        - pause: { }
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
        - name: app1
          image: ghcr.io/vasil-cf/app1:1.0.0
          ports:
            - containerPort: 3000
          env:
            - name: host
              valueFrom:
                configMapKeyRef:
                  name: app1-configmap
                  key: host
            - name: port
              valueFrom:
                configMapKeyRef:
                  name: app1-configmap
                  key: port
      imagePullSecrets:
        - name: ghcr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.app1.service_stable }}"
spec:
  selector:
    app: app1
  ports:
    - protocol: TCP
      port: {{ .Values.app1.port }}
      targetPort: {{ .Values.app1.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.app1.service_canary }}"
spec:
  selector:
    app: app1
  ports:
    - protocol: TCP
      port: {{ .Values.app1.port }}
      targetPort: {{ .Values.app1.port }}
