apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
        - name: app2
          image: ghcr.io/vasil-cf/app2:1.1.0
          ports:
            - containerPort: 3000
          env:
            - name: host
              valueFrom:
                configMapKeyRef:
                  name: app2-configmap
                  key: host
            - name: port
              valueFrom:
                configMapKeyRef:
                  name: app2-configmap
                  key: port
            - name: app1_host
              valueFrom:
                configMapKeyRef:
                  name: app2-configmap
                  key: app1_host
            - name: app1_port
              valueFrom:
                configMapKeyRef:
                  name: app2-configmap
                  key: app1_port
      imagePullSecrets:
        - name: ghcr-secret
---
{{ if .Values.app2.isToDeployService -}}
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.app2.service }}"
spec:
  selector:
    app: app2
  ports:
    - protocol: TCP
      port: {{ .Values.app2.port }}
      targetPort: {{ .Values.app2.port }}
{{- end }}