apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: exercise-argo-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/vasil-cf/kubernetes-test.git
    targetRevision: main
    path: helm-chart/exercise
  destination:
    server: https://kubernetes.default.svc
    namespace: exercise-argo

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
