app1:
  host: "0.0.0.0"
  port: "3000"
  service_stable: "app1-service-stable"
  service_canary: "app1-service-canary"

app2:
  host: "0.0.0.0"
  port: "3000"
  isToDeployService: true
  service: "app2-service"
