apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-deployment
spec:
  template:
    spec:
      containers:
        - name: app1
          resources:
            limits:
              memory: 512Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2-deployment
spec:
  template:
    spec:
      containers:
        - name: app2
          resources:
            limits:
              memory: 512Mi
